### ISSUE TITLE
No mitigation against Meltdown attack

### ISSUE THREAD

**Issue by seirl** [arjun024/mkernel#12]
`mkernel` doesn't unmap vulnerable memory pages from userspace, which makes it vulnerable to the Meltdown attack on Intel CPUs. I advise against using it for critical cloud services as long as this issue remains.

**Comment by ghost** [comment]
I know this is old, but I don't think you even understand what this project is. It's a bare minimum kernel that simply prints a message to the screen and stops. It doesn't have a userspace, it doesn't have paging implemented. It also doesn't have internet, so you can't use it for the cloud. 
Someone please close this.

**Comment by seirl** [comment]
(I totally forgot what the context of this issue was, but it was definitely a joke.)
