### ISSUE TITLE
Invalid magic number

### ISSUE THREAD

**Issue by eshwartm** [arjun024/mkernel#6]
Hi, 
I am using Ubuntu 14.04.
I followed the steps on your blog, added an entry to grub.cfg like this

    menuentry 'My Kernel' { 
       set root='hd0,msdos1'
       #my kernel executable is kernel-101, I even tried simply /kernel-101 btw
       multiboot /boot/kernel-101 ro
    }

And I updated my grub with
`sudo update-grub`

And when I restart, it throws me 
`error: invalid magic number`

What could be the problem?

**Comment by arjun024** [comment]
Thanks @eshwartm for submitting the issue. I just checked the grub man (http://www.gnu.org/software/grub/manual/grub.html) and it says:
_GRUB requires that the device name be enclosed with '(' and ')'_

Could you just try with the parentheses added:
```
set root='(hd0,msdos1)'
```
Please do let me know if this worked out for you or not.
In case it did work, you could submit a PR to the ubuntu config if you wish to do so.

**Comment by richardkiene** [comment]
@arjun024 @eshwartm I just verified that the parentheses are indeed necessary and fix this issue.
